
// The AVLTree class is provided 
import java.util.Scanner;

public class Test {

    public static void main(String[] args) {
        {
        //creating Scanner class object to get input from user  
        Scanner sc = new Scanner(System.in);

        // create object of ConstructAVLTree class object for costructing AVL Tree  
        AVLTree<Integer, Integer> obj = new AVLTree();

        char choice;    //initialize a character type variable to choice   

        // perform operation of AVL Tree using switch  
        //do      
        //{  
        int ch;
        AVLNode<Integer,Integer> tempNode;
        do
        {
        System.out.println("\nSelect an operation:\n");
        System.out.println("1. Insert a node");
        System.out.println("2. Search a node");
        System.out.println("3. Get total number of nodes in AVL Tree");
        System.out.println("4. Is AVL Tree empty?");
        System.out.println("5. Remove all nodes from AVL Tree");
        System.out.println("6. Display AVL Tree in Post order");
        System.out.println("7. Display AVL Tree in Pre order");
        System.out.println("8. Display AVL Tree in In order");
        System.out.println("9. Display if P is an external node");
        System.out.println("10. Display if key is present in a tree, changes the value of this field of this entry to new value");
        System.out.println("11. exit");
        //}

        //get choice from user  
         ch = sc.nextInt();
        switch (ch) {
            case 1:
                System.out.println("Please enter an element to insert in AVL Tree");
                obj.insert(sc.nextInt());
                break;
            case 2:
                System.out.println("Enter integer element to search");
                tempNode=obj.search(sc.nextInt());
                if(tempNode==null)
                {
                    System.out.println("Not found!");
                }
                else
                {                    
                    System.out.println(tempNode.element());
                }
                break;
            case 3:
                System.out.println(obj.countNodes());
                break;
            case 4:
                System.out.println(obj.isEmpty());
                break;
            case 5:
                obj.makeEmpty();
                System.out.println("\nTree Cleared successfully");
                break;
            case 6:
                System.out.println("\nDisplay AVL Tree in Post order");
                obj.postorder();
                break;
            case 7:
                System.out.println("\nDisplay AVL Tree in Pre order");
                obj.preorder();
                break;
            case 8:
                System.out.println("\nDisplay AVL Tree in In order");
                obj.inorder();
                break;
            case 9:
                System.out.println("\nDisplay if p is external node");
                //obj.external();  
                break;
            case 10:
                System.out.println("\nDisplay if key is present in a tree, changes the value field of this entry to new value");
                
                System.out.println("Enter integer element to search");
                tempNode=obj.search(sc.nextInt());
                if(tempNode==null)
                {
                    System.out.println("Not found!");
                }
                else
                {                    
                    System.out.println("Enter new value");
                    int value=sc.nextInt();
                    tempNode.element().setValue(value);
                }
                
                obj.search(ch);  
                break;
            default:
                System.out.println("\n ");
                break;

        }
        } while(ch!=11);
        }
        {
        // CASE 11 to check if the Tree is valid AVL tree. Here you will check the AVL tree generated by reading the file word.txt is a valid AVL.
//        In another test for case 11, you will consider the following and provide these values to your AVL tree program to check if it will create a balance tree?
//        Remember isBST() and isBalanced() are the functions you will create and pass them the values of t1 and t2 as specified below. For valid AVL tree, it should be BST first then we can check 		if its AVL or not

        System.out.println("11. Check the tree is it is valid AVL Tree");


        
       
            AVLNode<Integer,Integer> t1 = 
                    new AVLNode<Integer,Integer>(new DictEntry<Integer,Integer>(1,1),null,null);

            t1.setLeft(new AVLNode<Integer,Integer>(new DictEntry<Integer,Integer>(2,1),null,null));

            t1.setRight(new AVLNode<Integer,Integer>(new DictEntry<Integer,Integer>(3,1),null,null));

            t1.right().setLeft(new AVLNode<Integer,Integer>(new DictEntry<Integer,Integer>(4,1),null,null));

            t1.right().setRight(new AVLNode<Integer,Integer>(new DictEntry<Integer,Integer>(5,1),null,null)); 

     

            AVLNode<Integer,Integer>  t2 = new AVLNode<Integer,Integer>(new DictEntry<Integer,Integer>(15,1),null,null);

            t2.setLeft(new AVLNode<Integer,Integer>(new DictEntry<Integer,Integer>(5,1),null,null));

            t2.setRight(new AVLNode<Integer,Integer>(new DictEntry<Integer,Integer>(20,1),null,null));

            t2.right().setLeft(new AVLNode<Integer,Integer>(new DictEntry<Integer,Integer>(18,1),null,null));

            t2.right().setRight(new AVLNode<Integer,Integer>(new DictEntry<Integer,Integer>(23,1),null,null));

            t2.left().setLeft(new AVLNode<Integer,Integer>(new DictEntry<Integer,Integer>(4,1),null,null));

            t2.left().setRight(new AVLNode<Integer,Integer>(new DictEntry<Integer,Integer>(6,1),null,null));

     

            if (t1.isBST(t1) && t1.isBalanced(t1))

                System.out.println("Tree t1 is AVL tree");

            else

                System.out.println("Tree t1 is not AVL tree");

     

            if (t2.isBST(t2) && t2.isBalanced(t2))

                System.out.println("Tree t2 is AVL tree");

            else

                System.out.println("Tree t2 is not AVL tree");
                        }
    }
}
